"""
Test Script Generator - Convert SpecTestPilot output to executable tests.

Takes the JSON test cases from SpecTestPilot and generates:
1. Postman Collection (Newman-compatible)
2. pytest test script (Python)
3. curl commands (Shell script)
4. requests test script (Python)

Usage:
    python test_script_generator.py --input tests.json --format postman --output collection.json
"""

import json
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
import uuid


@dataclass
class TestCase:
    """Parsed test case from SpecTestPilot output."""
    test_id: str
    name: str
    method: str
    path: str
    headers: Dict[str, str]
    query_params: Dict[str, str] 
    path_params: Dict[str, str]
    body: Dict[str, Any]
    expected_status: int
    expected_schema: Optional[str] = None
    expected_fields: List[Dict] = None
    objective: str = ""
    notes: str = ""
    
    @classmethod
    def from_spectestpilot(cls, test_data: Dict) -> "TestCase":
        """Convert SpecTestPilot test case to our format."""
        endpoint = test_data.get("endpoint", {})
        request = test_data.get("request", {})
        assertions = test_data.get("assertions", [])
        
        # Find status code assertion
        expected_status = 200
        expected_schema = None
        expected_fields = []
        
        for assertion in assertions:
            if assertion.get("type") == "status_code":
                expected_status = assertion.get("expected", 200)
            elif assertion.get("type") == "schema":
                expected_schema = assertion.get("expected")
            elif assertion.get("type") == "field":
                expected_fields.append(assertion)
        
        return cls(
            test_id=test_data.get("test_id", ""),
            name=test_data.get("name", ""),
            method=endpoint.get("method", "GET").upper(),
            path=endpoint.get("path", "/"),
            headers=request.get("headers", {}),
            query_params=request.get("query_params", {}),
            path_params=request.get("path_params", {}),
            body=request.get("body", {}),
            expected_status=expected_status,
            expected_schema=expected_schema,
            expected_fields=expected_fields,
            objective=test_data.get("objective", ""),
            notes=test_data.get("notes", "")
        )


class PostmanGenerator:
    """Generate Postman collection from test cases."""
    
    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url.rstrip("/")
    
    def generate(self, test_cases: List[TestCase], api_name: str = "Generated API Tests") -> Dict:
        """Generate Postman collection."""
        collection = {
            "info": {
                "name": api_name,
                "description": f"Generated by SpecTestPilot - {len(test_cases)} test cases",
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
            },
            "auth": {
                "type": "bearer",
                "bearer": [{"key": "token", "value": "{{auth_token}}", "type": "string"}]
            },
            "variable": [
                {"key": "base_url", "value": self.base_url},
                {"key": "auth_token", "value": "test-token-123"}
            ],
            "item": []
        }
        
        # Group tests by endpoint
        endpoint_groups = {}
        for test in test_cases:
            endpoint_key = f"{test.method} {test.path}"
            if endpoint_key not in endpoint_groups:
                endpoint_groups[endpoint_key] = []
            endpoint_groups[endpoint_key].append(test)
        
        # Create test items
        for endpoint_key, tests in endpoint_groups.items():
            folder = {
                "name": endpoint_key,
                "item": []
            }
            
            for test in tests:
                item = self._create_postman_item(test)
                folder["item"].append(item)
            
            collection["item"].append(folder)
        
        return collection
    
    def _create_postman_item(self, test: TestCase) -> Dict:
        """Create a single Postman test item."""
        # Build URL with path parameters
        url_path = test.path
        for param, value in test.path_params.items():
            placeholder = value if value != f"<{param}>" else "123"
            url_path = url_path.replace(f"{{{param}}}", placeholder)
        
        url = {
            "raw": f"{{{{base_url}}}}{url_path}",
            "host": ["{{base_url}}"],
            "path": url_path.strip("/").split("/") if url_path != "/" else [],
        }
        
        # Add query parameters
        if test.query_params:
            url["query"] = [
                {"key": key, "value": value.replace(f"<{key}>", "test_value")}
                for key, value in test.query_params.items()
                if value  # Skip empty values
            ]
        
        # Build request
        request = {
            "method": test.method,
            "header": [
                {"key": key, "value": value, "type": "text"}
                for key, value in test.headers.items()
            ],
            "url": url
        }
        
        # Add body for POST/PUT/PATCH
        if test.method in ["POST", "PUT", "PATCH"] and test.body:
            # Generate sample body
            sample_body = self._generate_sample_body(test)
            request["body"] = {
                "mode": "raw",
                "raw": json.dumps(sample_body, indent=2),
                "options": {"raw": {"language": "json"}}
            }
        
        # Add tests/assertions
        test_script = self._generate_postman_tests(test)
        
        return {
            "name": test.name,
            "event": [
                {
                    "listen": "test",
                    "script": {
                        "exec": test_script,
                        "type": "text/javascript"
                    }
                }
            ],
            "request": request
        }
    
    def _generate_sample_body(self, test: TestCase) -> Dict:
        """Generate sample request body based on test case."""
        if test.body:
            return test.body
        
        # Generate sample based on endpoint
        if "pet" in test.path.lower():
            return {"name": "Buddy", "species": "dog", "age": 3}
        elif "user" in test.path.lower():
            return {"username": "testuser", "email": "test@example.com"}
        elif "order" in test.path.lower():
            return {"product_id": 123, "quantity": 1}
        else:
            return {"data": "test"}
    
    def _generate_postman_tests(self, test: TestCase) -> List[str]:
        """Generate Postman test assertions."""
        tests = [
            f'pm.test("{test.name}", function () {{',
            f'    pm.response.to.have.status({test.expected_status});'
        ]
        
        # Add schema validation if specified
        if test.expected_schema:
            tests.append('    pm.response.to.be.json;')
        
        # Add field validations
        for field in test.expected_fields:
            path = field.get("path", "")
            rule = field.get("rule", "exists")
            if path and "error" in path:
                tests.append('    pm.expect(pm.response.json()).to.have.property("error");')
        
        # Add common validations based on status
        if test.expected_status == 200:
            tests.append('    pm.response.to.be.json;')
        elif test.expected_status in [400, 401, 403, 404]:
            tests.append('    pm.expect(pm.response.json()).to.have.property("error");')
        
        tests.append('});')
        return tests


class PytestGenerator:
    """Generate pytest test script."""
    
    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url.rstrip("/")
    
    def generate(self, test_cases: List[TestCase], api_name: str = "Generated API Tests") -> str:
        """Generate pytest test script."""
        lines = [
            '"""',
            f'{api_name}',
            f'Generated by SpecTestPilot - {len(test_cases)} test cases',
            '"""',
            '',
            'import requests',
            'import pytest',
            'import json',
            '',
            f'BASE_URL = "{self.base_url}"',
            'AUTH_TOKEN = "test-token-123"',
            '',
            'def get_headers(include_auth=True):',
            '    """Get common headers."""',
            '    headers = {"Content-Type": "application/json"}',
            '    if include_auth:',
            '        headers["Authorization"] = f"Bearer {AUTH_TOKEN}"',
            '    return headers',
            '',
        ]
        
        # Generate test functions
        for test in test_cases:
            lines.extend(self._generate_pytest_function(test))
            lines.append('')
        
        return '\n'.join(lines)
    
    def _generate_pytest_function(self, test: TestCase) -> List[str]:
        """Generate a single pytest test function."""
        func_name = self._sanitize_function_name(test.name)
        
        lines = [
            f'def test_{func_name}():',
            f'    """',
            f'    {test.objective or test.name}',
            f'    Expected: {test.expected_status}',
            f'    """',
        ]
        
        # Build URL
        url = f'BASE_URL + "{test.path}"'
        for param, value in test.path_params.items():
            placeholder = "123" if value == f"<{param}>" else value
            url = url.replace(f"{{{param}}}", placeholder)
        
        # Add headers
        include_auth = any("auth" in h.lower() for h in test.headers.keys())
        lines.append(f'    headers = get_headers(include_auth={include_auth})')
        
        # Add query params
        if test.query_params:
            params_dict = {k: "test_value" if v.startswith("<") else v 
                          for k, v in test.query_params.items() if v}
            lines.append(f'    params = {params_dict}')
        else:
            lines.append('    params = {}')
        
        # Add body for POST/PUT/PATCH
        if test.method in ["POST", "PUT", "PATCH"]:
            sample_body = self._generate_sample_body(test)
            lines.append(f'    data = {json.dumps(sample_body)}')
            
            # Make request
            lines.extend([
                f'    response = requests.{test.method.lower()}(',
                f'        {url},',
                f'        headers=headers,',
                f'        params=params,',
                f'        data=data',
                f'    )'
            ])
        else:
            # GET/DELETE request
            lines.extend([
                f'    response = requests.{test.method.lower()}(',
                f'        {url},',
                f'        headers=headers,',
                f'        params=params',
                f'    )'
            ])
        
        # Add assertions
        lines.append('')
        lines.append(f'    # Assertions')
        lines.append(f'    assert response.status_code == {test.expected_status}')
        
        if test.expected_status == 200:
            lines.append('    assert response.headers["content-type"].startswith("application/json")')
            lines.append('    data = response.json()')
            lines.append('    assert isinstance(data, (dict, list))')
        
        elif test.expected_status in [400, 401, 403, 404]:
            lines.append('    if response.headers.get("content-type", "").startswith("application/json"):')
            lines.append('        error_data = response.json()')
            lines.append('        # FastAPI uses "detail", others might use "error" or "message"')
            lines.append('        assert "error" in error_data or "message" in error_data or "detail" in error_data')
        
        return lines
    
    def _sanitize_function_name(self, name: str) -> str:
        """Convert test name to valid Python function name."""
        # Remove special characters, replace spaces with underscores
        sanitized = ""
        for char in name.lower():
            if char.isalnum():
                sanitized += char
            elif char in " -/":
                sanitized += "_"
        
        # Remove consecutive underscores
        while "__" in sanitized:
            sanitized = sanitized.replace("__", "_")
        
        return sanitized.strip("_")
    
    def _generate_sample_body(self, test: TestCase) -> Dict:
        """Generate sample request body."""
        if test.body and any(test.body.values()):
            return test.body
        
        # Generate realistic data based on endpoint
        if "pet" in test.path.lower():
            return {"name": "Buddy", "species": "dog", "age": 3}
        elif "user" in test.path.lower():
            return {"username": "testuser", "email": "test@example.com", "name": "Test User"}
        elif "order" in test.path.lower():
            return {"product_id": 123, "quantity": 1, "price": 29.99}
        else:
            return {"test_field": "test_value"}


class CurlGenerator:
    """Generate curl commands."""
    
    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url.rstrip("/")
    
    def generate(self, test_cases: List[TestCase]) -> str:
        """Generate shell script with curl commands."""
        lines = [
            '#!/bin/bash',
            '# Generated API Tests - Curl Commands',
            f'# Base URL: {self.base_url}',
            '',
            'BASE_URL="' + self.base_url + '"',
            'AUTH_TOKEN="test-token-123"',
            '',
            'echo "🚀 Running API Tests..."',
            'echo "=========================="',
            '',
        ]
        
        for i, test in enumerate(test_cases):
            lines.extend(self._generate_curl_command(test, i + 1))
            lines.append('')
        
        lines.extend([
            'echo "=========================="',
            'echo "✅ All tests completed!"'
        ])
        
        return '\n'.join(lines)
    
    def _generate_curl_command(self, test: TestCase, test_num: int) -> List[str]:
        """Generate single curl command."""
        lines = [
            f'echo "Test {test_num}: {test.name}"',
            f'echo "Expected: {test.expected_status}"',
        ]
        
        # Build curl command
        curl_parts = ['curl']
        curl_parts.extend(['-w', '"\\nStatus: %{http_code}\\n"'])
        curl_parts.extend(['-s'])  # Silent
        
        # Add method
        if test.method != "GET":
            curl_parts.extend(['-X', test.method])
        
        # Add headers
        for key, value in test.headers.items():
            if key.lower() == 'authorization' and value == 'Bearer <token>':
                curl_parts.extend(['-H', f'"Authorization: Bearer $AUTH_TOKEN"'])
            else:
                curl_parts.extend(['-H', f'"{key}: {value}"'])
        
        # Add body
        if test.method in ["POST", "PUT", "PATCH"]:
            sample_body = self._generate_sample_body(test)
            if sample_body:
                curl_parts.extend(['-d', f"'{json.dumps(sample_body)}'"])
        
        # Build URL
        url = f"$BASE_URL{test.path}"
        for param, value in test.path_params.items():
            placeholder = "123" if value.startswith("<") else value
            url = url.replace(f"{{{param}}}", placeholder)
        
        # Add query params
        if test.query_params:
            query_parts = []
            for key, value in test.query_params.items():
                if value and not value.startswith("<"):
                    query_parts.append(f"{key}={value}")
                else:
                    query_parts.append(f"{key}=test_value")
            if query_parts:
                url += "?" + "&".join(query_parts)
        
        curl_parts.append(f'"{url}"')
        
        lines.append(' '.join(curl_parts))
        lines.append('echo "---"')
        
        return lines
    
    def _generate_sample_body(self, test: TestCase) -> Dict:
        """Generate sample body for curl."""
        if test.body and any(test.body.values()):
            return test.body
        
        if "pet" in test.path.lower():
            return {"name": "Buddy", "species": "dog"}
        elif "user" in test.path.lower():
            return {"username": "testuser", "email": "test@example.com"}
        else:
            return {"data": "test"}


class TestScriptGenerator:
    """Main generator that supports multiple output formats."""
    
    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url
        self.postman_generator = PostmanGenerator(base_url)
        self.pytest_generator = PytestGenerator(base_url)
        self.curl_generator = CurlGenerator(base_url)
    
    def load_spectestpilot_output(self, file_path: str) -> List[TestCase]:
        """Load and parse SpecTestPilot JSON output."""
        with open(file_path, 'r') as f:
            data = json.load(f)
        
        test_suite = data.get("test_suite", [])
        test_cases = []
        
        for test_data in test_suite:
            try:
                test_case = TestCase.from_spectestpilot(test_data)
                test_cases.append(test_case)
            except Exception as e:
                print(f"⚠️  Skipping invalid test case: {e}")
        
        return test_cases
    
    def generate_postman_collection(self, test_cases: List[TestCase], api_name: str = "") -> Dict:
        """Generate Postman collection."""
        return self.postman_generator.generate(test_cases, api_name)
    
    def generate_pytest_script(self, test_cases: List[TestCase], api_name: str = "") -> str:
        """Generate pytest script."""
        return self.pytest_generator.generate(test_cases, api_name)
    
    def generate_curl_script(self, test_cases: List[TestCase]) -> str:
        """Generate curl script."""
        return self.curl_generator.generate(test_cases)


def main():
    """CLI interface for test script generation."""
    parser = argparse.ArgumentParser(
        description="Convert SpecTestPilot output to executable tests",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Generate Postman collection
    python test_script_generator.py --input tests.json --format postman --output collection.json
    
    # Generate pytest script  
    python test_script_generator.py --input tests.json --format pytest --output test_api.py
    
    # Generate curl script
    python test_script_generator.py --input tests.json --format curl --output test_api.sh
        """
    )
    
    parser.add_argument("--input", "-i", required=True,
                       help="SpecTestPilot JSON output file")
    parser.add_argument("--format", "-f", 
                       choices=["postman", "pytest", "curl"],
                       default="postman",
                       help="Output format")
    parser.add_argument("--output", "-o", 
                       help="Output file (default: auto-generated)")
    parser.add_argument("--base-url", 
                       default="http://localhost:8000",
                       help="Base URL for API")
    parser.add_argument("--api-name",
                       help="API name for documentation")
    
    args = parser.parse_args()
    
    # Validate input file
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"❌ Input file not found: {args.input}")
        return
    
    # Create generator
    generator = TestScriptGenerator(args.base_url)
    
    # Load test cases
    print(f"📂 Loading SpecTestPilot output from: {args.input}")
    test_cases = generator.load_spectestpilot_output(args.input)
    print(f"✅ Loaded {len(test_cases)} test cases")
    
    # Generate output
    api_name = args.api_name or input_path.stem.replace("_", " ").title()
    
    if args.format == "postman":
        output = generator.generate_postman_collection(test_cases, api_name)
        default_filename = f"{input_path.stem}_postman.json"
        output_content = json.dumps(output, indent=2)
        
    elif args.format == "pytest":
        output_content = generator.generate_pytest_script(test_cases, api_name)
        default_filename = f"test_{input_path.stem}.py"
        
    elif args.format == "curl":
        output_content = generator.generate_curl_script(test_cases)
        default_filename = f"{input_path.stem}_curl.sh"
    
    # Determine output file
    output_path = args.output or default_filename
    
    # Save output
    Path(output_path).write_text(output_content)
    
    print(f"✅ Generated {args.format} tests: {output_path}")
    print(f"📊 {len(test_cases)} test cases converted")
    
    # Show sample
    print(f"\n📄 Sample {args.format} output:")
    print("=" * 40)
    print(output_content[:500] + "..." if len(output_content) > 500 else output_content)


if __name__ == "__main__":
    main()
